services:
  store_manager_app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - mongo
      - mongo_init
      - mysql
    stdin_open: true
    tty: true  

  mongo_init:
    build: .
    volumes:
      - .:/app
    depends_on:
      - mongo
    command: python /app/db-init/init_mongo.py
    restart: "no"

  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo-data:/data/db

  mysql:
    image: mysql:8
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: store_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mongo-data:
  mysql-data:
