name: example_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Creer fichier .env
        run: |
          echo "DB_HOST=localhost" >> .env
          echo "DB_NAME=mydb" >> .env
          echo "DB_USERNAME=user" >> .env
          echo "DB_PASSWORD=pass" >> .env

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Déployer sur la VM LOG430
        if: success()
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 10.194.32.200
          username: log430
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd brokerx/Lab-01-Client-Server-Persistence-DAO-RDBMS-NoSQL-/
            git pull
           

